### ISSUE TITLE
点击下一篇页面没正常跳转

### ISSUE THREAD

**Issue by Zwtttt** [prodigytech-doc/learning-docs#110]
### 所属页面地址

https://learning.ark.online/main-course/games-bomber-game/create-project.html#_2-%E5%88%9B%E5%BB%BA%E5%85%A5%E5%8F%A3%E7%B1%BB

### 选中内容

下一篇
创建工程

### 请选择反馈的问题类型

缺少信息 - 我想了解更多信息

**Comment by Othanse** [comment]
027会有更新
