### ISSUE TITLE
使用方法简化（建议）

### ISSUE THREAD

**Issue by zaixia** [prodigytech-doc/learning-docs#173]
### 所属页面地址

https://learning.ark.online/monster-course/4.attack-monster.html#_5-%E5%88%A4%E6%96%AD%E6%A3%80%E6%B5%8B%E7%BB%93%E6%9E%9C

### 选中内容

MonsterScirpt

### 请选择反馈的问题类型

缺少信息 - 我想了解更多信息

### 补充说明

感谢提供了很多示例可供参考，获取脚本的方式有很多中，这种的确是可以有效的执行后续的方法，能否通过getScriptByName可以更快速准确的获取指定的脚本呢

**Comment by Othanse** [comment]
不错的建议，之前版本这个API有点小问题所以绕了下，现在已经修复，可以使用了
