### ISSUE TITLE
（建议）更改怪物死亡方式

### ISSUE THREAD

**Issue by zaixia** [prodigytech-doc/learning-docs#174]
### 所属页面地址

https://learning.ark.online/monster-course/5.attack-feedback.html#_3-%E6%80%AA%E7%89%A9%E6%AD%BB%E4%BA%A1%E7%89%B9%E6%95%88

### 选中内容

setVisibility

### 请选择反馈的问题类型

缺少信息 - 我想了解更多信息

### 补充说明

怪物死亡的方法是隐藏怪物，建议更改位置、布娃娃的方式或者同时关闭怪物的碰撞方法。玩家在此区域操作攻击方法，依然是会对怪物造成伤害的。

**Comment by onionkingdom** [comment]
建议收到了！ 我们在下次更新教程时会注意这一点 ，感谢你的反馈😘
